# Release Management Workflow Template
#
# This template automates the release process including:
# - Version bumping
# - Changelog generation
# - Release creation
# - Asset publishing
#
# Triggered by: version tags (v*.*.*)

name: Release Management

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
      prerelease:
        description: 'Is this a pre-release?'
        required: false
        default: 'false'

jobs:
  # Validate release
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Extract version info
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
            PRERELEASE="${{ github.event.inputs.prerelease }}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
            PRERELEASE="false"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is_prerelease=$PRERELEASE" >> $GITHUB_OUTPUT
          echo "Release version: $VERSION (prerelease: $PRERELEASE)"

  # Build release artifacts
  build-artifacts:
    name: Build Release Artifacts
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build release packages
        run: |
          echo "Building release artifacts for v${{ needs.validate.outputs.version }}..."
          # Add your build commands here
          mkdir -p dist
          echo "Release v${{ needs.validate.outputs.version }}" > dist/release.txt
      
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: dist/

  # Generate changelog
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Generate changelog
        run: |
          echo "# Changelog for v${{ needs.validate.outputs.version }}" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "## Changes" >> CHANGELOG.md
          git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> CHANGELOG.md || echo "- Initial release" >> CHANGELOG.md
      
      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: CHANGELOG.md

  # Create GitHub release
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [validate, build-artifacts, generate-changelog]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
      
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating release v${{ needs.validate.outputs.version }}..."
          # gh release create v${{ needs.validate.outputs.version }} \
          #   --title "Release v${{ needs.validate.outputs.version }}" \
          #   --notes-file changelog/CHANGELOG.md \
          #   --prerelease=${{ needs.validate.outputs.is_prerelease }} \
          #   release-artifacts/*
          echo "✓ Release created successfully"

  # Post-release notifications
  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: create-release
    if: always()
    steps:
      - name: Notify team
        run: |
          echo "Sending release notifications..."
          # Add notification logic (Slack, email, etc.)
