name: 'Release Please Action'
description: 'Runs release-please for a specific path'
inputs:
  path:
    description: 'Path to the package'
    required: true
  package-name:
    description: 'Name of the package'
    required: true
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: google-github-actions/release-please-action@v4
      with:
        path: ${{ inputs.path }}
        package-name: ${{ inputs.package-name }}
        release-type: simple
        token: ${{ inputs.token }}